// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package user

import (
	"time"
)

type Address struct {
	ID        int
	UserID    int
	Street    string
	City      string
	ZipCode   string
	Latitude  float64
	Longitude float64
}

type User struct {
	ID          int
	Name        string
	PhoneNumber string
	Role        string
	CreatedAt   time.Time
}
