// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package order

import (
	"time"
)

type Order struct {
	ID         int
	UserID     int
	TotalPrice float64
	CreatedAt  time.Time
}

type OrderAddress struct {
	ID        int
	OrderID   int
	Street    string
	City      string
	ZipCode   string
	Latitude  float64
	Longitude float64
}
